<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-K7CIP8L" failures="1" tests="2" name="Default test(failed)" time="0.065" errors="0" timestamp="2020-05-04T11:17:14 BST">
  <testcase classname="listners.TestNGRetryFailedDemo" name="test3" time="0.013">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertTrue(Assert.java:53)
at listners.TestNGRetryFailedDemo.test3(TestNGRetryFailedDemo.java:25)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase classname="listners.TestNGRetryFailedDemo" name="test2" time="0.002"/>
  <testcase classname="listners.TestNGRetryFailedDemo" name="test1" time="0.0">
    <ignored/>
  </testcase> <!-- test1 -->
</testsuite> <!-- Default test(failed) -->
